apiVersion: apps/v1
kind: Deployment
metadata:
  name: catfacts
  namespace: catfacts
spec:
  selector:
    matchLabels:
      app: catfacts
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: catfacts
    spec:
      containers:
      - name: app
        image: catfacts/catfacts-fastapi
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 32Mi
            cpu: 100m
